export default [
    {
        name:'Profile',
        iconType:'Material',
        iconName:'face-profile'
    },
    {
        name:'Settings',
        iconType:'Feather',
        iconName:'settings'
    },
    {
        name:'Saved Items',
        iconType:'Material',
        iconName:'bookmark-check-outline'
    },
    {
        name:'Refer a Friend!',
        iconType:'FontAwesome5',
        iconName:'user-friends'
    },
    {
        name:'Home',
        iconType:'FontAwesome5',
        iconName:''
    },
    {
        name:'registration',
        iconType:'FontAwesome5',
        iconName:''
    },
    {
        name:'Events',
        iconType:'FontAwesome5',
        iconName:''
    },
    {
        name:'Home',
        iconType:'FontAwesome5',
        iconName:''
    },
]
